class AuditLogEvents:
    LOGS = {"user_log": {"name": "User Logs", "events": ["User-Signup-Initiated",
                                                         "User-Signup-Completed",
                                                         "User-signin-initiated",
                                                         "User-signin-completed",
                                                         "User-Logout-completed",
                                                         "Fitbit-Integration",
                                                         "Pain Score-submit",
                                                         "Pain Score-update",
                                                         "Satisfaction Score-Submit",
                                                         "Satisfaction Score-update",
                                                         "Recommendation-View",
                                                         "Rewards-View",
                                                         "Survey-Submit",
                                                         "Educational Content-View",
                                                         "Daily Pain Journal-Submit",
                                                         "Daily Pain Journal-Update",
                                                         "Insight-View-Personal",
                                                         "Insight-View-Community",
                                                         "Insight-Export",
                                                         "Journal-Submit",
                                                         "Journal-Update",
                                                         "Adverse Event-Submit",
                                                         "Settings-Profile-Submit",
                                                         ]},

            "admin_log": {"name": "Admin Logs", "events": ["Admin-login-initiated",
                                                           "Admin-login-completed",
                                                           "Admin-Logout-Completed",
                                                           "Admin-Home-View",
                                                           "Subject-Add",
                                                           "Subject-Edit",
                                                           "Subject-Delete",
                                                           "Subject-Import",
                                                           "Subject-Export-Details",
                                                           "Subject-Export-Pain Details",
                                                           "Subject-Export-Insights Details",
                                                           "Survey-Create",
                                                           "Survey-Edit",
                                                           "Survey-Report-Export",
                                                           "Dosing-Add",
                                                           "Medication-Add",
                                                           "Medication-Edit",
                                                           "Medication-Delete",
                                                           "Recommendation-Add",
                                                           "Recommendation-Edit",
                                                           "Recommendation-Delete",
                                                           "BodyParts-Add",
                                                           "BodyParts-Edit",
                                                           "BodyParts-Delete",
                                                           "Admin-Add",
                                                           "Admin-Import",
                                                           "Admin-Edit",
                                                           "Admin-Delete",
                                                           "Event-Type-Add",
                                                           "Event-Type-Edit",
                                                           "Event-Type-Delete",
                                                           "EduContent-Video-Add",
                                                           "EduContent-Video-Edit",
                                                           "EduContent-Video-Delete",
                                                           "Setting-Profile-Submit",
                                                           "Setting-Profile-Update",
                                                           "Rewards-Submit",
                                                           "Redemption-Submit",
                                                           "Resource-Add",
                                                           "Resource-Edit",
                                                           "Resource-Delete"]}
            }
